service: t-bot

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048 # optional, in MB, default is 1024
  timeout: 29 # optional, in seconds, default is 6
  lambdaHashingVersion: 20201221

functions:
  telegram:
    handler: src/index.handler
    environment: ${file(env.yml)}
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: patch
          cors: true
      - http:
          path: /
          method: put
          cors: true
      - http:
          path: /
          method: delete
          cors: true
